### ISSUE TITLE
Add support for selfhosted habitica installations

### ISSUE THREAD

**Issue by arthurlutz** [philadams/habitica#12]
https://habitica.com is hard wired in the code. It would be nice to be able to use this tool with self hosted habitica installations.

Places the URL is hard wired: 
- API_URI_BASE in api.py and 
- HABITICA_TASKS_PAGE in core.py
- load_netrc() (core.py) should use a domain given as option or found in .netrc

**Comment by philadams-zz** [comment]
That's a really great point - I wasn't aware folk were doing that! This is definitely on the TODO list.

**Comment by philadams-zz** [comment]
Fixed! Thanks to @Lertsenem for most of the changes.
