### ISSUE TITLE
I'm having problems with setting up habitica

### ISSUE THREAD

**Issue by huesitos** [philadams/habitica#16]
When I write habitica server, I get a good response. However, when I try to see my status, I get this error

Traceback (most recent call last):
  File "/usr/local/bin/habitica", line 13, in <module>
    habitica.cli()
  File "/usr/local/lib/python2.7/dist-packages/habitica/core.py", line 279, in cli
    quest_progress = qp_tmp.values()[0]['count']
TypeError: 'int' object has no attribute '**getitem**'

I created the auth.cfg file where it has to be and completed the fields. Any of what is happening?

**Comment by philadams-zz** [comment]
Added a comment to your PR - take a look.

Thanks for investigating, looks like the API changed.
