### ISSUE TITLE
print_task_list uses bytes instead of strings

### ISSUE THREAD

**Issue by josephholsten** [philadams/habitica#19]
when using python3, `print_task_list` makes for ugliness.

```
$ habitica dailies
[ ] 1 b'[x] Meh'
```

which comes from `task['text'].encode('utf8')`. we could use `task['text'].encode('utf8').decode()`, but that seems terrible. I'm not even entirely convinced by https://github.com/philadams/habitica/commit/1b4f7b2fdebb3e57d0128cf58c762a13925c2f82, but my python is really rusty.

**Comment by philadams-zz** [comment]
I'll add this to the backlog - thanks.

I guess the discussion over when the world should just move (all at once?) to Python v3 is still ongoing?
