### ISSUE TITLE
2 Issues: Dailes not resetting and my colors are grey, organge and green (not the right colors for dailies)

### ISSUE THREAD

**Issue by Lilkarebear** [philadams/habitica#20]

**Comment by philadams-zz** [comment]
Colors: intriguing! Can you attach a screenshot to this thread? And, what OS/terminal are you using?

**Comment by Lilkarebear** [comment]
Hi Phil, 
I now understand why some are green and some are orange. It has to do with how consultant I am at completing a daily. Orange means it's getting redder and green means it's getting bluer. I don't know why some dailies were grey when they were actually due. I'm not having that problem right now though. Thank you for getting back to me.

**Comment by philadams-zz** [comment]
Of course! Hope you're enjoying Habitica - and kicking ass with your habits :)

**Comment by Lilkarebear** [comment]
I am, thank you! :)

**Comment by philadams-zz** [comment]
👍
