### ISSUE TITLE
Import Tasks

### ISSUE THREAD

**Issue by sebelk** [philadams/habitica#21]
Hi,

It would be nice if we can import tasks from a text file containing something such as:

```
+ Gimnasio [médium]
+ Hice una nota con las cosas buenas del día [easy]
+/- Llegué a tiempo / Tarde [hard]
```

What do you think?

Thanks in advance!

**Comment by philadams-zz** [comment]
Interesting idea! Is there a standard format for Habitica tasks, when exported like this?
