### ISSUE TITLE
Test Version 3 of the API

### ISSUE THREAD

**Issue by crookedneighbor** [philadams/habitica#22]
We're looking for Habitica developers to try out the upcoming version 3 of the API. We are hoping that we will be ready to start testing within the next two weeks, but we're collecting testers now so that we can hit the ground running. Thanks very much for considering it, and feel free to let me know if you have any questions!

| [Sign Up!](https://docs.google.com/forms/d/1xXxZvSviR_s8K3I31bKXH6Dfc6Ud9TuTG66I90PdwQI/viewform) |
| --- |

**Comment by philadams-zz** [comment]
I've got a bunch of changes to make, it would be great to test them in v3. Most of the sign up form seems to be around being a beta tester for the official clients. Is this the same form to learn about how to prepare our 3P clients for v3?

**Comment by crookedneighbor** [comment]
There's a section about being a developer. Anyone that marks that section will get additional information about it.

**Comment by crookedneighbor** [comment]
Just letting you know that the testing phase is now over. Version 2 of the Habitica API will be officially [deactivated on July 15th](http://devs.habitica.com/api-v2-deprecation-notice/). 

[Here is a migration guide](http://devs.habitica.com/api-v2-v3-migration-guide/) for upgrading to version 3. If you have any questions, feel free to reach out on [Github](https://github.com/HabitRPG/habitrpg/issues) or the [Aspiring Comrades Guild](https://habitica.com/#/options/groups/guilds/2ff9822b-27f2-4774-98da-db349b57a38e).

**Comment by philadams-zz** [comment]
Thanks!

I need to look into the API anyway, seems that the ordering of tasks is now funny both in terms of adding and marking complete...

**Comment by crookedneighbor** [comment]
I'm not sure what you mean.

**Comment by philadams-zz** [comment]
Oh! Just that for some reason I wasn't getting a consistent ordering of TODOs from the API. Seems to all be resolved now. Merged a PR to update for v3 of the API - looks good!

Thanks - love Habitica :)
