### ISSUE TITLE
Broken API / syntacktic pull request / citation use for related utility

### ISSUE THREAD

**Issue by eringiglio** [philadams/habitica#25]
Hey, 

I'm currently trying to use your Python wrapper to create a Python utility that can sync between Todoist and Habitica, but the API update issue means that the master copy won't work as is. While I'm developing it, I don't have an issue using syntacktic's version with the API update (see the pull request), but it'd be awesome if by the time I finish this thing I can direct people straight to pip install habitica for the API wrapper and then whatever I wind up naming the syncer program. I think it'd be simpler. I know it's been a super short timeframe and not sure if this project is being very tightly monitored at this time, but I wanted to let you know before I did anything. 

Otherwise, how would you like me to cite your work when I finish my project? I'll default to linking your work here, obviously, with all attribution attached. 

Cheers,

Erin

**Comment by eringiglio** [comment]
Also, I apologize if this isn't the place for this comment! I'm new to using Github as a means of contacting and also creating open source utilities, so I'm still learning the norms of social interactions here.

**Comment by philadams-zz** [comment]
This is the right place! I've just been super busy at work and not prioritizing this.

I've merged the v3 PR and a couple others, things with habitica v0.0.15 seem to be working again.

Sync tool: nice!
