### ISSUE TITLE
Show the checklist count and optionally display the entire checklist

### ISSUE THREAD

**Issue by robertpateii** [philadams/habitica#26]
Hi Phil,

I use checklists a lot with habitica so it'd be really useful to have this CLI for it support them.

I've actually already developed this feature and will be posting a pull request for it soon. 

Is that something you'd be interested in accepting?

Thanks,

Rob

**Comment by gustiando** [comment]
@robertpateii was this ever merged? I'd love to be able to see checklists for my todos. Is there a more active version fork of this CLI?

**Comment by robertpateii** [comment]
It hasn't been merged. I tweeted at Phi yesterday. There are a handful of working forks, but I'd like to get his input before we rally around a different one.

**Comment by robertpateii** [comment]
Just as i was about to despair and start hunting for a fork Phil got back to me on twitter. said he'd do the API fix PR later this week. I guess that means i need to actually post my checklist code.

**Comment by gustiando** [comment]
Awesome! that's great news :)

**Comment by robertpateii** [comment]
Hey Gustavo @gumatias, I posted my PR with the checklists code. Just need Phil to come get caught up w/ all the PRs. My next PR will let you check off checklist items instead of just viewing them.

**Comment by philadams-zz** [comment]
Merging now...
