### ISSUE TITLE
Incompatible with Current Habitica API?

### ISSUE THREAD

**Issue by ghost** [philadams/habitica#28]
Whether downloading from this Github for "bleeding edge", or downloading simply using pip install, I'm kicked back by the Habitica API because supposedly this uses version 2.  Am I correct in saying the program is currently non-functional?  I don't see a ticket simply expressing this, so am creating this -- apologies if I am somehow duplicating or cluttering.

**Comment by jwodder** [comment]
FYI, there is currently an outstanding pull request that makes the program functional, but the repository owner hasn't reponded to it yet: #23

**Comment by ghost** [comment]
Thanks.  'habitica status' errored out with a 404 at https://habitica.com/api/v3/groups/party until I created a party (with just myself in it) -- otherwise, the patch works great.

**Comment by philadams-zz** [comment]
PR accepted.

I'll take a look at this party issue - thanks @WCityMike
