### ISSUE TITLE
Having problems with running "hrpg" 

### ISSUE THREAD

**Issue by annafung** [philadams/habitica#5]
I ran into an installation issue here:
! Installing the dependencies failed: Module 'Method::Signatures' is not installed, Module 'JSON::XS::Boolean' is not installed
! Bailing out the installation for WebService-HabitRPG-0.22.
21 distributions installed

And I think this is why I'm unable to actually run "hrpg" from the command line. Here's what I've got:

Malformed config file at ~/.hrpgrc

Traceback (most recent call last):
  File "//anaconda/bin/hrpg", line 13, in <module>
    hrpg.cli()
  File "//anaconda/lib/python2.7/site-packages/hrpg/core.py", line 133, in cli
    config = load_config(CONFIG_FILE)
  File "//anaconda/lib/python2.7/site-packages/hrpg/core.py", line 44, in load_config
    raise ValueError(err.msg)
AttributeError: 'exceptions.ValueError' object has no attribute 'msg'

**Comment by philadams-zz** [comment]
Hi @annafung! Can you enter exactly the commands you used trying to install `hrpg`?

I wonder if you've got potentially conflicting installs of this library and a Perl-based version? http://search.cpan.org/dist/WebService-HabitRPG/bin/hrpg

Should just be able to do a quick `pip install hrpg`, which should also install docopt and requests.

**Comment by philadams-zz** [comment]
Update: now, of course, it's `pip install habitica`. And, based on no new information in this thread, I'm closing this issue.
